# Generated by Django 5.0.7 on 2024-08-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_timesheet_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
