# Generated by Django 5.0.7 on 2024-08-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_summery_eventblock_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=50)),
                ('rule', models.TextField()),
                ('source', models.ForeignKey(choices=[('EXACT', 'Exact Match'), ('CONTAINS', 'Contains'), ('STARTS_WITH', 'Starts With'), ('ENDS_WITH', 'Ends With'), ('REGEX', 'Regular Expression')], on_delete=django.db.models.deletion.CASCADE, to='project.source')),
            ],
        ),
    ]
