# Generated by Django 5.0.7 on 2024-08-06 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_sourcerule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetday',
            name='timesheet',
        ),
        migrations.AddField(
            model_name='eventblock',
            name='uploaded_to_calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sourcerule',
            name='source',
            field=models.ForeignKey(choices=[('EXACT', 'Exact'), ('CONTAINS', 'Contains'), ('STARTS_WITH', 'Starts_With'), ('END_WITH', 'End_With'), ('REGEX', 'Regex')], on_delete=django.db.models.deletion.CASCADE, to='project.source'),
        ),
        migrations.DeleteModel(
            name='Timesheet',
        ),
        migrations.DeleteModel(
            name='TimesheetDay',
        ),
    ]
