# Generated by Django 5.0.7 on 2024-08-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_projectdaysummary_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='eraser_embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
