# Generated by Django 5.0.7 on 2024-08-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_eraser_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='monthly_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
