# Generated by Django 5.0.7 on 2024-08-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_monthly_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='monthly_hours',
        ),
        migrations.AddField(
            model_name='project',
            name='monthly_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
