# Generated by Django 5.0.7 on 2024-08-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_client_project_client_timeentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='harvest_client_id',
            new_name='harvest_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='harvest_project_id',
            new_name='harvest_id',
        ),
        migrations.RenameField(
            model_name='timeentry',
            old_name='harvest_time_entry_id',
            new_name='harvest_id',
        ),
    ]
