# Generated by Django 5.0.7 on 2024-08-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_rename_harvest_client_id_client_harvest_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeentry',
            old_name='duration',
            new_name='hours',
        ),
    ]
