# Generated by Django 5.0.7 on 2024-08-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_rename_duration_timeentry_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='user',
        ),
    ]
