# Generated by Django 5.0.7 on 2024-08-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_project_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='billable',
            field=models.BooleanField(default=False),
        ),
    ]
